#!/usr/bin/env python3
"""Assemble main.tex from paper_template.tex + numbers read from the result JSONs.

    python3 build.py [results_dir]

Reads paper_template.tex, replaces the %%MACROS%% and %%ROWS:<name>%% markers
with LaTeX generated by make_tables.py, and writes a self-contained main.tex.
No number in main.tex is typed by hand: re-run this script after any change to
the result files.
"""
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
RESULTS = Path(sys.argv[1]) if len(sys.argv) > 1 else HERE.parent / "results"
TABLES = HERE / "tables"

FIGURES = HERE / "figures"

subprocess.run(
    [sys.executable, str(HERE / "make_tables.py"), str(RESULTS), str(TABLES)],
    check=True,
)
subprocess.run(
    [sys.executable, str(HERE / "make_figures.py"), str(RESULTS), str(FIGURES)],
    check=True,
)

template = (HERE / "paper_template.tex").read_text(encoding="utf-8")
out_lines = []
for line in template.splitlines():
    s = line.strip()
    if s == "%%MACROS%%":
        out_lines.append((TABLES / "macros.tex").read_text(encoding="utf-8").rstrip())
    elif s.startswith("%%ROWS:") and s.endswith("%%"):
        name = s[len("%%ROWS:"):-2]
        body = (TABLES / f"{name}.tex").read_text(encoding="utf-8").rstrip()
        if body.endswith("%"):
            body = body[:-1].rstrip()
        out_lines.append(body)
    else:
        out_lines.append(line)

(HERE / "main.tex").write_text("\n".join(out_lines) + "\n", encoding="utf-8")
print(f"wrote {HERE / 'main.tex'} ({len(out_lines)} lines)")
